# Generated by Django 2.2.6 on 2020-04-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='Balance',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='credit',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='total_amount_paid',
            field=models.FloatField(null=True),
        ),
    ]
