# Generated by Django 2.2.6 on 2019-11-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='Description',
            field=models.TextField(max_length=300),
        ),
    ]
