# Generated by Django 2.2.6 on 2020-04-27 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='damage',
            options={'get_latest_by': 'date', 'ordering': ('-date',)},
        ),
        migrations.AddField(
            model_name='tenant',
            name='registered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
