# Generated by Django 2.2.6 on 2020-04-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20200427_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChekedOutTenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('checked_by', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
            ],
        ),
    ]
