# Generated by Django 2.2.6 on 2019-11-21 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20191118_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='floor_number',
        ),
    ]
