# Generated by Django 2.2.6 on 2019-11-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_remove_unit_floor_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='floor_number',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
