# Generated by Django 2.2.6 on 2019-11-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_unit_floor_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='floor_number',
            field=models.CharField(choices=[('Ground', 'Ground'), ('Parking-Bay', 'Parking-Bay')], max_length=300, null=True),
        ),
    ]
