# Generated by Django 2.2.6 on 2019-11-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20191121_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='floor_number',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
