# Generated by Django 2.2.6 on 2019-11-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_auto_20191121_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='floor_number',
            field=models.CharField(choices=[('Ground', 'Ground'), ('Parking-Bay', 'Parking-Bay'), ('first', 'first'), ('second', 'second'), ('third', 'third'), ('fourth', 'fourth'), ('fifth', 'fifth'), ('sixth', 'sixth'), ('seventh', 'seventh'), ('eighth', 'eighth'), ('ninth', 'ninth')], max_length=300, null=True),
        ),
    ]
