# Generated by Django 2.2.6 on 2019-11-26 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20191126_1136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ('-date_added', 'property')},
        ),
    ]
