# Generated by Django 2.2.6 on 2019-11-26 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20191126_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ('property',)},
        ),
        migrations.AlterField(
            model_name='rent',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_rent', to='property.Unit'),
        ),
    ]
