# Generated by Django 2.2.6 on 2019-11-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20191126_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='Balance',
            field=models.FloatField(null=True),
        ),
    ]
