# Generated by Django 2.2.6 on 2019-11-26 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_rent_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='Balance',
        ),
    ]
