# Generated by Django 2.2.6 on 2020-01-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20200122_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='occupied',
            field=models.BooleanField(default=False),
        ),
    ]
