# Generated by Django 2.2.6 on 2020-01-25 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_auto_20200125_0847'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rent',
            unique_together={('unit', 'year', 'month')},
        ),
    ]
