# Generated by Django 2.2.6 on 2020-01-27 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0018_auto_20200125_1136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rent',
            options={'ordering': ('-date_paid', '-year', 'month', 'unit')},
        ),
    ]
