# Generated by Django 2.2.6 on 2020-01-27 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_auto_20200127_1043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rent',
            options={'ordering': ('-year', 'month', 'unit')},
        ),
    ]
