# Generated by Django 2.2.6 on 2020-02-25 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0020_auto_20200127_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=2),
        ),
        migrations.AlterField(
            model_name='rent',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=2),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='unit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='unit_tenant', to='property.Unit'),
        ),
    ]
