# Generated by Django 2.2.6 on 2020-03-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0022_auto_20200226_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=3),
        ),
        migrations.AlterField(
            model_name='rent',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=3),
        ),
        migrations.AlterField(
            model_name='unit',
            name='floor_number',
            field=models.CharField(choices=[('Ground', 'Ground'), ('Parking-Bay', 'Parking-Bay'), ('zeroth', 'zeroth'), ('first', 'first'), ('second', 'second'), ('third', 'third'), ('fourth', 'fourth'), ('fifth', 'fifth'), ('sixth', 'sixth'), ('seventh', 'seventh'), ('eighth', 'eighth'), ('ninth', 'ninth'), ('tenth', 'tenth'), ('eleventh', 'eleventh'), ('twelfth', 'twelfth'), ('thirteenth', 'thirteenth'), ('fourteenth', 'fourteenth'), ('fifteenth', 'fifteenth'), ('sixteenth', 'sixteenth'), ('seventeenth', 'seventeenth'), ('eighteenth', 'eighteenth'), ('nineteenth', 'nineteenth'), ('twentieth', 'twentieth'), ('twenty-first', 'twenty-first'), ('twenty-second', 'twenty-second'), ('twenty-third', 'twenty-third'), ('twenty-fourth', 'twenty-fourth'), ('twenty-fifth', 'twenty-fifth'), ('twenty-sixth', 'twenty-sixth'), ('twenty-seventh', 'twenty-seventh'), ('twenty-eighth', 'twenty-eighth'), ('twenty-ninth', 'twenty-ninth'), ('thirtieth', 'thirtieth'), ('thirty-first', 'thirty-first'), ('thirty-second', 'thirty-second'), ('thirty-third', 'thirty-third'), ('thirty-fourth', 'thirty-fourth'), ('thirty-fifth', 'thirty-fifth'), ('thirty-sixth', 'thirty-sixth'), ('thirty-seventh', 'thirty-seventh'), ('thirty-eighth', 'thirty-eighth'), ('thirty-ninth', 'thirty-ninth')], max_length=300, null=True),
        ),
    ]
