# Generated by Django 2.2.6 on 2020-03-06 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0023_auto_20200305_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='total_amount_paid',
            new_name='rent',
        ),
    ]
